### ISSUE TITLE
Add gda-sqlite dep on deb packing

### ISSUE THREAD

**Issue by naaando** [robertsanseries/karim#20]

**Comment by robertsanseries** [comment]
Is it really necessary? Since I'm making use of libgda?

**Comment by naaando** [comment]
Test it, remove gda-sqlite then run install the package and run, will crash by not finding sqlite driver.

**Comment by robertsanseries** [comment]
@naaando the application was developed for the loki version of the elementary operating system (this version already has sqlite by default). However, I will add to the dependency. Many thanks for the contribution.
